apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${csi-spc-name}
  namespace: default
spec:
  provider: vault
  parameters:
    vaultAddress: "http://external-vault:8200"
    roleName: "${vault-role}"
    objects: |
      - objectName: "username"
        secretPath: "${vault-secret-mount}/data/${vault-secret-path}"
        secretKey: "username"
      - objectName: "password"
        secretPath: "${vault-secret-mount}/data/${vault-secret-path}"
        secretKey: "password"
  secretObjects:
    - secretName: csi-secret
      type: Opaque
      data:
      - objectName: username
        key: username
      - objectName: password
        key: password
